# Generated by Django 5.1.1 on 2024-10-14 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fake_news_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsarticle",
            name="title",
        ),
    ]
